// GERADO A PARTIR DE Processos.xlsx (fonte da verdade do modelo de dados).
// Alterações de conteúdo devem ser feitas pela tela de Administração da
// plataforma; este arquivo representa a carga inicial do banco.

'use strict';

const SETORES = [
  { nome: "Paralegal", auxiliar: 0, ordem: 1 },
  { nome: "Fiscal", auxiliar: 0, ordem: 2 },
  { nome: "Departamento Pessoal", auxiliar: 0, ordem: 3 },
  { nome: "Contábil", auxiliar: 0, ordem: 4 },
  { nome: "Jurídico", auxiliar: 0, ordem: 5 },
  { nome: "Administrativo", auxiliar: 0, ordem: 6 },
  { nome: "Diretoria", auxiliar: 0, ordem: 7 },
  { nome: "Sócios", auxiliar: 1, ordem: 8 },
  { nome: "Financeiro", auxiliar: 1, ordem: 9 },
  { nome: "Cliente", auxiliar: 1, ordem: 10 },
  { nome: "TI", auxiliar: 1, ordem: 11 },
  { nome: "Qualidade", auxiliar: 1, ordem: 12 },
];

const TIPOS_PROCESSO = [
  { nome: "Constituição de Empresa", ativo: 1, ordem: 1 },
  { nome: "Baixa de Empresa", ativo: 1, ordem: 2 },
  { nome: "Alteração Contratual", ativo: 1, ordem: 3 },
  { nome: "Alteração de Endereço", ativo: 1, ordem: 4 },
  { nome: "Alteração de CNAE", ativo: 1, ordem: 5 },
  { nome: "Alteração de Capital Social", ativo: 1, ordem: 6 },
  { nome: "Entrada de Sócio", ativo: 1, ordem: 7 },
  { nome: "Saída de Sócio", ativo: 1, ordem: 8 },
  { nome: "Transformação Empresarial", ativo: 1, ordem: 9 },
  { nome: "Abertura de Filial", ativo: 1, ordem: 10 },
  { nome: "Encerramento de Filial", ativo: 1, ordem: 11 },
  { nome: "Regularização Cadastral", ativo: 1, ordem: 12 },
  { nome: "Emissão de Certidões", ativo: 1, ordem: 13 },
  { nome: "Incorporação", ativo: 1, ordem: 14 },
  { nome: "Fusão", ativo: 1, ordem: 15 },
  { nome: "Cisão Total", ativo: 1, ordem: 16 },
  { nome: "Cisão Parcial", ativo: 1, ordem: 17 },
  { nome: "Recuperação de Empresa", ativo: 1, ordem: 18 },
  { nome: "Reativação de CNPJ", ativo: 1, ordem: 19 },
  { nome: "Consolidação Contratual", ativo: 1, ordem: 20 },
  { nome: "Desenquadramento do MEI", ativo: 1, ordem: 21 },
  { nome: "Enquadramento no Simples Nacional", ativo: 1, ordem: 22 },
  { nome: "Alteração de Natureza Jurídica", ativo: 1, ordem: 23 },
  { nome: "Registro de Marca (Acompanhamento)", ativo: 1, ordem: 24 },
  { nome: "Emissão de Alvarás e Licenças", ativo: 1, ordem: 25 },
];

const STATUS_PROCESSO = [
  { nome: "Aberto", ordem: 1, final: 0, espera: 0 },
  { nome: "Em Análise Fiscal", ordem: 2, final: 0, espera: 0 },
  { nome: "Em Análise Departamento Pessoal", ordem: 3, final: 0, espera: 0 },
  { nome: "Em Análise Contábil", ordem: 4, final: 0, espera: 0 },
  { nome: "Em Análise Jurídica", ordem: 5, final: 0, espera: 0 },
  { nome: "Aguardando Cliente", ordem: 6, final: 0, espera: 1 },
  { nome: "Aguardando Assinaturas", ordem: 7, final: 0, espera: 1 },
  { nome: "Aguardando Junta Comercial", ordem: 8, final: 0, espera: 1 },
  { nome: "Aguardando Receita Federal", ordem: 9, final: 0, espera: 1 },
  { nome: "Aguardando Prefeitura", ordem: 10, final: 0, espera: 1 },
  { nome: "Impedido", ordem: 11, final: 0, espera: 0 },
  { nome: "Liberado", ordem: 12, final: 0, espera: 0 },
  { nome: "Concluído", ordem: 13, final: 1, espera: 0 },
  { nome: "Cancelado", ordem: 14, final: 1, espera: 0 },
];

// tipo === null  =>  linha "Todos" da planilha (aplicada a qualquer processo)
const CHECKLIST_MODELO = [
  { tipo: "Constituição de Empresa", setor: "Paralegal", item: "Contrato Social elaborado?", obrigatorio: 1 },
  { tipo: "Constituição de Empresa", setor: "Paralegal", item: "Viabilidade aprovada?", obrigatorio: 1 },
  { tipo: "Constituição de Empresa", setor: "Paralegal", item: "DBE aprovado?", obrigatorio: 1 },
  { tipo: "Constituição de Empresa", setor: "Sócios", item: "Contrato assinado pelos sócios?", obrigatorio: 1 },
  { tipo: "Baixa de Empresa", setor: "Fiscal", item: "Possui débitos federais?", obrigatorio: 1 },
  { tipo: "Baixa de Empresa", setor: "Fiscal", item: "Possui débitos estaduais?", obrigatorio: 1 },
  { tipo: "Baixa de Empresa", setor: "Fiscal", item: "Possui débitos municipais?", obrigatorio: 1 },
  { tipo: "Baixa de Empresa", setor: "Departamento Pessoal", item: "Existem funcionários ativos?", obrigatorio: 1 },
  { tipo: "Baixa de Empresa", setor: "Contábil", item: "ECD transmitida?", obrigatorio: 1 },
  { tipo: "Baixa de Empresa", setor: "Paralegal", item: "DBE emitido?", obrigatorio: 1 },
  { tipo: "Alteração Contratual", setor: "Paralegal", item: "Minuta elaborada?", obrigatorio: 1 },
  { tipo: "Alteração Contratual", setor: "Sócios", item: "Aprovação dos sócios obtida?", obrigatorio: 1 },
  { tipo: "Alteração de Endereço", setor: "Paralegal", item: "Alteração contratual elaborada?", obrigatorio: 1 },
  { tipo: "Alteração de Endereço", setor: "Fiscal", item: "Inscrição municipal atualizada?", obrigatorio: 1 },
  { tipo: "Alteração de CNAE", setor: "Fiscal", item: "Impactos tributários avaliados?", obrigatorio: 1 },
  { tipo: "Alteração de CNAE", setor: "Paralegal", item: "Alteração protocolada?", obrigatorio: 1 },
  { tipo: "Alteração de Capital Social", setor: "Contábil", item: "Capital integralizado conferido?", obrigatorio: 1 },
  { tipo: "Alteração de Capital Social", setor: "Sócios", item: "Percentuais aprovados?", obrigatorio: 1 },
  { tipo: "Entrada de Sócio", setor: "Sócios", item: "Documentação do novo sócio recebida?", obrigatorio: 1 },
  { tipo: "Entrada de Sócio", setor: "Paralegal", item: "Alteração registrada?", obrigatorio: 1 },
  { tipo: "Saída de Sócio", setor: "Sócios", item: "Termo de retirada assinado?", obrigatorio: 1 },
  { tipo: "Saída de Sócio", setor: "Contábil", item: "Apuração de haveres realizada?", obrigatorio: 1 },
  { tipo: "Transformação Empresarial", setor: "Paralegal", item: "Nova natureza jurídica definida?", obrigatorio: 1 },
  { tipo: "Transformação Empresarial", setor: "Fiscal", item: "Impactos tributários avaliados?", obrigatorio: 1 },
  { tipo: "Abertura de Filial", setor: "Paralegal", item: "Viabilidade aprovada?", obrigatorio: 1 },
  { tipo: "Abertura de Filial", setor: "Fiscal", item: "Inscrições necessárias identificadas?", obrigatorio: 1 },
  { tipo: "Encerramento de Filial", setor: "Fiscal", item: "Existem débitos da filial?", obrigatorio: 1 },
  { tipo: "Encerramento de Filial", setor: "Paralegal", item: "Baixa protocolada?", obrigatorio: 1 },
  { tipo: "Regularização Cadastral", setor: "Paralegal", item: "Pendências identificadas?", obrigatorio: 1 },
  { tipo: "Regularização Cadastral", setor: "Fiscal", item: "Situação cadastral regularizada?", obrigatorio: 1 },
  { tipo: "Emissão de Certidões", setor: "Fiscal", item: "Certidões solicitadas?", obrigatorio: 1 },
  { tipo: "Emissão de Certidões", setor: "Paralegal", item: "Certidões entregues ao cliente?", obrigatorio: 1 },
  { tipo: "Incorporação", setor: "Fiscal", item: "Possui débitos federais?", obrigatorio: 1 },
  { tipo: "Incorporação", setor: "Contábil", item: "Balanço de incorporação elaborado?", obrigatorio: 1 },
  { tipo: "Incorporação", setor: "Departamento Pessoal", item: "Haverá transferência de empregados?", obrigatorio: 1 },
  { tipo: "Incorporação", setor: "Sócios", item: "Todos os sócios aprovaram a operação?", obrigatorio: 1 },
  { tipo: "Incorporação", setor: "Jurídico", item: "Parecer jurídico emitido?", obrigatorio: 0 },
  { tipo: "Fusão", setor: "Fiscal", item: "Certidões negativas emitidas?", obrigatorio: 1 },
  { tipo: "Fusão", setor: "Contábil", item: "Patrimônio consolidado?", obrigatorio: 1 },
  { tipo: "Fusão", setor: "Sócios", item: "Instrumento societário assinado?", obrigatorio: 1 },
  { tipo: "Cisão Total", setor: "Contábil", item: "Patrimônio segregado?", obrigatorio: 1 },
  { tipo: "Cisão Total", setor: "Sócios", item: "Responsabilidades definidas?", obrigatorio: 1 },
  { tipo: "Cisão Parcial", setor: "Contábil", item: "Percentual da cisão definido?", obrigatorio: 1 },
  { tipo: "Cisão Parcial", setor: "Fiscal", item: "Pendências tributárias avaliadas?", obrigatorio: 1 },
  { tipo: "Recuperação de Empresa", setor: "Jurídico", item: "Plano de recuperação elaborado?", obrigatorio: 1 },
  { tipo: "Recuperação de Empresa", setor: "Contábil", item: "Demonstrações atualizadas?", obrigatorio: 1 },
  { tipo: "Reativação de CNPJ", setor: "Fiscal", item: "Pendências identificadas?", obrigatorio: 1 },
  { tipo: "Reativação de CNPJ", setor: "Paralegal", item: "Pedido de reativação protocolado?", obrigatorio: 1 },
  { tipo: "Consolidação Contratual", setor: "Paralegal", item: "Contrato consolidado elaborado?", obrigatorio: 1 },
  { tipo: "Consolidação Contratual", setor: "Sócios", item: "Aprovação dos sócios registrada?", obrigatorio: 1 },
  { tipo: "Desenquadramento do MEI", setor: "Fiscal", item: "Motivo do desenquadramento identificado?", obrigatorio: 1 },
  { tipo: "Desenquadramento do MEI", setor: "Paralegal", item: "Comunicação realizada?", obrigatorio: 1 },
  { tipo: "Enquadramento no Simples Nacional", setor: "Fiscal", item: "Empresa elegível ao Simples?", obrigatorio: 1 },
  { tipo: "Enquadramento no Simples Nacional", setor: "Fiscal", item: "Opção transmitida?", obrigatorio: 1 },
  { tipo: "Alteração de Natureza Jurídica", setor: "Paralegal", item: "Nova natureza jurídica validada?", obrigatorio: 1 },
  { tipo: "Alteração de Natureza Jurídica", setor: "Contábil", item: "Impactos contábeis avaliados?", obrigatorio: 1 },
  { tipo: "Registro de Marca (Acompanhamento)", setor: "Paralegal", item: "Pedido protocolado no INPI?", obrigatorio: 1 },
  { tipo: "Registro de Marca (Acompanhamento)", setor: "Cliente", item: "Documentação recebida?", obrigatorio: 1 },
  { tipo: "Emissão de Alvarás e Licenças", setor: "Paralegal", item: "Solicitação realizada junto ao órgão competente?", obrigatorio: 1 },
  { tipo: "Emissão de Alvarás e Licenças", setor: "Fiscal", item: "Taxas recolhidas?", obrigatorio: 1 },
  { tipo: null, setor: "Financeiro", item: "Cliente está adimplente?", obrigatorio: 0 },
  { tipo: null, setor: "Cliente", item: "Documentação completa recebida?", obrigatorio: 1 },
  { tipo: null, setor: "TI", item: "Certificado digital válido?", obrigatorio: 0 },
  { tipo: null, setor: "Qualidade", item: "Checklist revisado?", obrigatorio: 1 },
];

const USUARIOS = [
  { nome: "Gabriela", login: "gabriela", email: "gabriela@jsgrilo.com.br", setor: "Fiscal", perfil: "Administrador", status: "Ativo" },
  { nome: "Ana Paula", login: "ana.paula", email: "ana.paula@jsgrilo.com.br", setor: "Fiscal", perfil: "Usuário", status: "Ativo" },
  { nome: "Cecilia", login: "cecilia", email: "cecilia@jsgrilo.com.br", setor: "Fiscal", perfil: "Usuário", status: "Ativo" },
  { nome: "Geilza", login: "geilza", email: "geilza@jsgrilo.com.br", setor: "Fiscal", perfil: "Usuário", status: "Ativo" },
  { nome: "Elidiane", login: "elidiane", email: "elidiane@jsgrilo.com.br", setor: "Administrativo", perfil: "Administrador", status: "Ativo" },
  { nome: "Ana Lucia", login: "ana.lucia", email: "ana.lucia@jsgrilo.com.br", setor: "Departamento Pessoal", perfil: "Usuário", status: "Ativo" },
  { nome: "Lalá", login: "lala", email: "lala@jsgrilo.com.br", setor: "Departamento Pessoal", perfil: "Usuário", status: "Ativo" },
  { nome: "Samuel", login: "samuel", email: "samuel@jsgrilo.com.br", setor: "Departamento Pessoal", perfil: "Usuário", status: "Ativo" },
  { nome: "Crislane", login: "crislane", email: "crislane@jsgrilo.com.br", setor: "Departamento Pessoal", perfil: "Usuário", status: "Ativo" },
  { nome: "Jacqueline", login: "jacqueline", email: "jacqueline@jsgrilo.com.br", setor: "Diretoria", perfil: "Administrador", status: "Ativo" },
  { nome: "Andreia", login: "andreia", email: "andreia@jsgrilo.com.br", setor: "Financeiro", perfil: "Usuário", status: "Ativo" },
  { nome: "Daiane", login: "daiane", email: "daiane@jsgrilo.com.br", setor: "Contábil", perfil: "Usuário", status: "Ativo" },
  { nome: "Nayara", login: "nayara", email: "nayara@jsgrilo.com.br", setor: "Contábil", perfil: "Usuário", status: "Ativo" },
  { nome: "Jocileide", login: "jocileide", email: "jocileide@jsgrilo.com.br", setor: "Contábil", perfil: "Administrador", status: "Ativo" },
  { nome: "Anna Clara", login: "anna.clara", email: "anna.clara@jsgrilo.com.br", setor: "Administrativo", perfil: "Usuário", status: "Ativo" },
];
// Tabela PARAMETROS: além de chave/valor, cada parâmetro carrega tipo,
// categoria e descrição para que a tela de Administração possa renderizar
// os controles corretos (checkbox, número, texto, e-mail).
const PARAMETROS = [
  // ---------------------------------------------------------- Numeração
  { chave: 'PREFIXO_PROCESSO', valor: 'PR', tipo: 'texto', categoria: 'Numeração', descricao: 'Prefixo do número do processo (ex.: PR).' },
  { chave: 'ANO_PROCESSO', valor: '2026', tipo: 'numero', categoria: 'Numeração', descricao: 'Ano corrente da numeração. Ao virar o ano, a sequência reinicia automaticamente.' },
  { chave: 'PROXIMO_PROCESSO', valor: '1', tipo: 'numero', categoria: 'Numeração', descricao: 'Próximo número sequencial a ser utilizado.' },
  { chave: 'DIGITOS_PROCESSO', valor: '4', tipo: 'numero', categoria: 'Numeração', descricao: 'Quantidade de dígitos do sequencial (4 => 0001).' },

  // ------------------------------------------------------- Notificações
  { chave: 'EMAIL_NOTIFICACAO', valor: 'Sim', tipo: 'booleano', categoria: 'Notificações', descricao: 'Chave geral: liga/desliga o envio de e-mails.' },
  { chave: 'EMAIL_ADMIN', valor: 'contato@jsgrilo.com.br', tipo: 'email', categoria: 'Notificações', descricao: 'E-mail do administrativo.' },
  { chave: 'EMAIL_FISCAL', valor: 'fiscal@jsgrilo.com.br', tipo: 'email', categoria: 'Notificações', descricao: 'E-mail do setor Fiscal.' },
  { chave: 'EMAIL_CONTABIL', valor: 'contabil@jsgrilo.com.br', tipo: 'email', categoria: 'Notificações', descricao: 'E-mail do setor Contábil.' },
  { chave: 'EMAIL_PESSOAL', valor: 'pessoal@jsgrilo.com.br', tipo: 'email', categoria: 'Notificações', descricao: 'E-mail do Departamento Pessoal.' },
  { chave: 'EMAIL_FINANCEIRO', valor: 'financeiro@jsgrilo.com.br', tipo: 'email', categoria: 'Notificações', descricao: 'E-mail do Financeiro.' },
  { chave: 'EMAIL_DIRETORIA', valor: 'jsgrilo.cont@gmail.com', tipo: 'email', categoria: 'Notificações', descricao: 'E-mail da Diretoria.' },
  { chave: 'EMAIL_PARALEGAL', valor: 'paralegal@jsgrilo.com.br', tipo: 'email', categoria: 'Notificações', descricao: 'E-mail do setor Paralegal.' },
  { chave: 'EMAIL_JURIDICO', valor: 'juridico@jsgrilo.com.br', tipo: 'email', categoria: 'Notificações', descricao: 'E-mail do setor Jurídico.' },
  { chave: 'NOTIFICAR_PARLEGAL', valor: 'Sim', tipo: 'booleano', categoria: 'Notificações', descricao: 'Notificar o setor Paralegal.' },
  { chave: 'NOTIFICAR_FISCAL', valor: 'Sim', tipo: 'booleano', categoria: 'Notificações', descricao: 'Notificar o setor Fiscal.' },
  { chave: 'NOTIFICAR_DP', valor: 'Sim', tipo: 'booleano', categoria: 'Notificações', descricao: 'Notificar o Departamento Pessoal.' },
  { chave: 'NOTIFICAR_CONTABIL', valor: 'Sim', tipo: 'booleano', categoria: 'Notificações', descricao: 'Notificar o setor Contábil.' },
  { chave: 'NOTIFICAR_JURIDICO', valor: 'Sim', tipo: 'booleano', categoria: 'Notificações', descricao: 'Notificar o setor Jurídico.' },
  { chave: 'ENVIAR_EMAIL_CONCLUSAO', valor: 'Sim', tipo: 'booleano', categoria: 'Notificações', descricao: 'Enviar e-mail quando o processo for concluído.' },
  { chave: 'ENVIAR_EMAIL_IMPEDIMENTO', valor: 'Sim', tipo: 'booleano', categoria: 'Notificações', descricao: 'Enviar e-mail quando um item for marcado como impedimento.' },

  // -------------------------------------------------------------- Prazos
  { chave: 'PRAZO_FISCAL_HORAS', valor: '24', tipo: 'numero', categoria: 'Prazos', descricao: 'Prazo (horas) para o Fiscal responder seus itens.' },
  { chave: 'PRAZO_DP_HORAS', valor: '24', tipo: 'numero', categoria: 'Prazos', descricao: 'Prazo (horas) para o Departamento Pessoal responder.' },
  { chave: 'PRAZO_CONTABIL_HORAS', valor: '24', tipo: 'numero', categoria: 'Prazos', descricao: 'Prazo (horas) para o Contábil responder.' },
  { chave: 'PRAZO_JURIDICO_HORAS', valor: '48', tipo: 'numero', categoria: 'Prazos', descricao: 'Prazo (horas) para o Jurídico responder.' },
  { chave: 'PRAZO_ASSINATURA_CLIENTE_DIAS', valor: '5', tipo: 'numero', categoria: 'Prazos', descricao: 'Prazo (dias) para o cliente assinar.' },
  { chave: 'PRAZO_PADRAO_PROCESSO_DIAS', valor: '15', tipo: 'numero', categoria: 'Prazos', descricao: 'Prazo padrão (dias) somado à abertura para calcular a previsão de conclusão.' },
  { chave: 'ALERTAR_PROCESSO_ATRASADO', valor: 'Sim', tipo: 'booleano', categoria: 'Prazos', descricao: 'Gerar alertas de processos atrasados.' },
  { chave: 'DIAS_ALERTA_ATRASO', valor: '3', tipo: 'numero', categoria: 'Prazos', descricao: 'Antecedência (dias) do alerta antes do vencimento.' },

  // ------------------------------------------------------------- Fluxo
  { chave: 'EXIGIR_APROVACAO_FISCAL', valor: 'Sim', tipo: 'booleano', categoria: 'Fluxo', descricao: 'Aprovação do Fiscal é obrigatória para concluir.' },
  { chave: 'EXIGIR_APROVACAO_DP', valor: 'Sim', tipo: 'booleano', categoria: 'Fluxo', descricao: 'Aprovação do Departamento Pessoal é obrigatória para concluir.' },
  { chave: 'EXIGIR_APROVACAO_CONTABIL', valor: 'Sim', tipo: 'booleano', categoria: 'Fluxo', descricao: 'Aprovação do Contábil é obrigatória para concluir.' },
  { chave: 'EXIGIR_APROVACAO_JURIDICA', valor: 'Não', tipo: 'booleano', categoria: 'Fluxo', descricao: 'Aprovação do Jurídico é obrigatória para concluir.' },
  { chave: 'PERMITIR_PULAR_ETAPAS', valor: 'Não', tipo: 'booleano', categoria: 'Fluxo', descricao: 'Permite alterar o status manualmente fora da ordem prevista.' },
  { chave: 'BLOQUEAR_CONCLUSAO_COM_PENDENCIA', valor: 'Sim', tipo: 'booleano', categoria: 'Fluxo', descricao: 'Impede concluir o processo com item obrigatório pendente ou impedido.' },
  { chave: 'EXIGIR_CHECKLIST_100', valor: 'Sim', tipo: 'booleano', categoria: 'Fluxo', descricao: 'Exige 100% do checklist (inclusive itens opcionais) para concluir.' },
  { chave: 'EXIGIR_OBSERVACAO_IMPEDIMENTO', valor: 'Sim', tipo: 'booleano', categoria: 'Fluxo', descricao: 'Descrição do impedimento é obrigatória.' },
  { chave: 'EXIGIR_REVISAO_FINAL', valor: 'Sim', tipo: 'booleano', categoria: 'Fluxo', descricao: 'Exige o item de Qualidade (revisão final) respondido antes de concluir.' },
  { chave: 'EXIGIR_DUPLA_CONFERENCIA', valor: 'Não', tipo: 'booleano', categoria: 'Fluxo', descricao: 'Exige que a resposta do item seja confirmada por um segundo colaborador.' },
  { chave: 'EXIGIR_APROVACAO_GESTOR', valor: 'Sim', tipo: 'booleano', categoria: 'Fluxo', descricao: 'Somente Administrador/Diretoria pode concluir o processo.' },
  { chave: 'UTILIZAR_VIABILIDADE', valor: 'Sim', tipo: 'booleano', categoria: 'Fluxo', descricao: 'Fluxo considera a etapa de viabilidade (Junta Comercial).' },
  { chave: 'EXIGIR_DBE', valor: 'Sim', tipo: 'booleano', categoria: 'Fluxo', descricao: 'Fluxo considera a emissão do DBE.' },
  { chave: 'EXIGIR_CERTIDAO_NEGATIVA', valor: 'Sim', tipo: 'booleano', categoria: 'Fluxo', descricao: 'Fluxo considera certidões negativas.' },
  { chave: 'EXIGIR_CERTIFICADO_DIGITAL', valor: 'Sim', tipo: 'booleano', categoria: 'Fluxo', descricao: 'Fluxo considera certificado digital válido.' },
  { chave: 'EXIGIR_ASSINATURA_ELETRONICA', valor: 'Sim', tipo: 'booleano', categoria: 'Fluxo', descricao: 'Fluxo considera assinatura eletrônica.' },

  // ---------------------------------------------------------- Dashboard
  { chave: 'EXIBIR_GRAFICOS', valor: 'Sim', tipo: 'booleano', categoria: 'Dashboard', descricao: 'Exibir gráficos no dashboard.' },
  { chave: 'EXIBIR_TEMPO_MEDIO', valor: 'Sim', tipo: 'booleano', categoria: 'Dashboard', descricao: 'Exibir tempo médio de conclusão por tipo.' },
  { chave: 'EXIBIR_PROCESSOS_IMPEDIDOS', valor: 'Sim', tipo: 'booleano', categoria: 'Dashboard', descricao: 'Exibir painel de processos impedidos.' },
  { chave: 'EXIBIR_PROCESSOS_CONCLUIDOS', valor: 'Sim', tipo: 'booleano', categoria: 'Dashboard', descricao: 'Exibir painel de processos concluídos no período.' },
  { chave: 'EXIBIR_PRODUTIVIDADE', valor: 'Sim', tipo: 'booleano', categoria: 'Dashboard', descricao: 'Exibir produtividade por setor.' },
  { chave: 'EXIBIR_RANKING_COLABORADORES', valor: 'Sim', tipo: 'booleano', categoria: 'Dashboard', descricao: 'Exibir ranking de colaboradores.' },
  { chave: 'META_PROCESSOS_MES', valor: '30', tipo: 'numero', categoria: 'Dashboard', descricao: 'Meta mensal de processos concluídos.' },

  // -------------------------------------------------- Documentos/Relatórios
  { chave: 'GERAR_PDF_CHECKLIST', valor: 'Sim', tipo: 'booleano', categoria: 'Documentos', descricao: 'Habilita o PDF do checklist preenchido.' },
  { chave: 'GERAR_RELATORIO_FINAL', valor: 'Sim', tipo: 'booleano', categoria: 'Documentos', descricao: 'Habilita o PDF do relatório final do processo.' },
  { chave: 'EXIGIR_UPLOAD_DOCUMENTOS', valor: 'Sim', tipo: 'booleano', categoria: 'Documentos', descricao: 'Exige ao menos um documento anexado para concluir o processo.' },
  { chave: 'SALVAR_DOCUMENTOS_DRIVE', valor: 'Sim', tipo: 'booleano', categoria: 'Documentos', descricao: 'Enviar cópia dos documentos ao Google Drive (requer credenciais).' },
  { chave: 'PASTA_DRIVE_PROCESSOS', valor: 'ID_DA_PASTA', tipo: 'texto', categoria: 'Documentos', descricao: 'ID da pasta do Google Drive onde os documentos são arquivados.' },

  // ------------------------------------------------------------ Auditoria
  { chave: 'REGISTRAR_HISTORICO', valor: 'Sim', tipo: 'booleano', categoria: 'Auditoria', descricao: 'Registrar ações no histórico do processo.' },
  { chave: 'REGISTRAR_LOGS', valor: 'Sim', tipo: 'booleano', categoria: 'Auditoria', descricao: 'Registrar logs técnicos de acesso.' },
  { chave: 'BACKUP_AUTOMATICO', valor: 'Sim', tipo: 'booleano', categoria: 'Auditoria', descricao: 'Executar backup automático diário do banco.' },
  { chave: 'DIAS_RETENCAO_LOG', valor: '365', tipo: 'numero', categoria: 'Auditoria', descricao: 'Dias de retenção dos logs.' },

  // ---------------------------------------------------------- Integrações
  { chave: 'INTEGRAR_GOOGLE_CHAT', valor: 'Sim', tipo: 'booleano', categoria: 'Integrações', descricao: 'Enviar avisos para um espaço do Google Chat (webhook).' },
  { chave: 'WEBHOOK_GOOGLE_CHAT', valor: '', tipo: 'texto', categoria: 'Integrações', descricao: 'URL do webhook do Google Chat.' },
  { chave: 'INTEGRAR_WHATSAPP', valor: 'Não', tipo: 'booleano', categoria: 'Integrações', descricao: 'Integração prevista, ainda não implementada.' },
  { chave: 'INTEGRAR_ONVIO', valor: 'Não', tipo: 'booleano', categoria: 'Integrações', descricao: 'Integração prevista, ainda não implementada.' },
  { chave: 'INTEGRAR_DOMINIO', valor: 'Não', tipo: 'booleano', categoria: 'Integrações', descricao: 'Integração prevista, ainda não implementada.' },
  { chave: 'INTEGRAR_ECAC', valor: 'Não', tipo: 'booleano', categoria: 'Integrações', descricao: 'Integração prevista, ainda não implementada.' },
];

module.exports = { SETORES, TIPOS_PROCESSO, STATUS_PROCESSO, CHECKLIST_MODELO, USUARIOS, PARAMETROS };
